changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.6.0.cjs

npmRegistries:
  "https://npm.pkg.github.com":
    npmAuthToken: ${NPM_PRIVATE_REGISTRY_TOKEN:-}

npmScopes:
  "ezstaking":
    npmAuthToken: ${NPM_PRIVATE_REGISTRY_TOKEN:-}
